services:
  password-keeper:
    image: postgres:13
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: passwordkeeper