apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-keeper-api
  labels:
    app: password-keeper-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-keeper-api
  template:
    metadata:
      labels:
        app: password-keeper-api
    spec:
      containers:
        - name: password-keeper-api
          image: 'dmitriykuzin/password-keeper:1.0.3'
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres-db-service
---
kind: Service
apiVersion: v1
metadata:
  name: password-keeper-service
spec:
  selector:
    app: password-keeper-api
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minik-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: dk-dev.com
      http:
        paths:
          - path: /pk(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: password-keeper-service
                port:
                  number: 80